### ISSUE TITLE
Documentación del uso del modelo por laderas, geo_Horton

### ISSUE THREAD

**Issue by Scastil** [nicolas998/WMF#23]
Mejorar la descripción de las propiedades del simuBasin definido por laderas, y de las laderas mismas.
Ejemplos; describir  self.nhills, diferencias de propiedades de celdas para modelType='hills' y modelType='cells'... cositas de esas...

wmf.cu.stram_long() funciona sin necesidad de definir SimuBasin por 'hills'.. pareciera que la cuenca definiera por defecto las propiedades de los dos tipos de modelType

**Comment by nicolas998** [comment]
Dame una mejor descripción de las mejoras que se sugieren, es para yo poder entrar a corregir cada una. como una lista: EJ:
1. Una ayuda sobre **hills** y **cells**
2. ...
3. ..
4.

**Comment by Scastil** [comment]
Corregir documentación de función self.GetGeo_Horton()

'CellHorton_Hill : Orden de horton de cada ladera.\n'\
'CellHorton_Stream : Orden de horton de cada elemento de cauce.\n'\

Lo anterior está herrado, ambas funciones listan el orden de horton de cada celda.

**Comment by Scastil** [comment]
Ampliar documentación sobre funciones geomorgológicas
p.e. set_Geomorphology() ... wmf.models.stream_long, etc

**Comment by nicolas998** [comment]
Sobre el comentario de horton, acabo de revisar y si son diferentes, en uno muestra toda la cuenca y en otro sólo sobre los cauces.

**Comment by nicolas998** [comment]
ya se ha puesto un mayor detalle sobre las variables.
