### ISSUE TITLE
wmf.SimuBasin.Save_SimuBasin: Bug al guardar si no se ha asignado la geomorfología

### ISSUE THREAD

**Issue by nicolas998** [nicolas998/WMF#27]
La función presenta un **bug** por el cual no deja guardar el **.nc** si no se ha invocado antes la función:
**cu.set_Geomorphology**.

Se sugiere corregir realizando una prueba al interior de la misma función, si se lanza la excepcioń que la función estime desto de manera automática, debe hacer lo siguiente:
- Avisar que no se han seteado param geomorfológicos.
- Hacerlo con las condiciones por defecto de los umbrales.
- Avisar con que condiciones esta haciendo eso.

**Comment by Scastil** [comment]
Parece que cuando se guarda la red de drenaje (cu.Save_Net2Map) lo hace con con un umbral de trazado por defecto (1000?), y no con el determinado al trazar la cuenca (wmf.SimuBasin)

**Comment by nicolas998** [comment]
Corregidos ambos errores, ahora la función **wmf.SimuBasin.Save_Net2Map** toma por defecto el umbral del elemento y lo otro ya se aplica cuando se guarda la cuenca.
