### ISSUE TITLE
wmf.Basin.Plot_basin(vec = vec), cuando esta función se le pasa un vec ya no trabaja bien.

### ISSUE THREAD

**Issue by nicolas998** [nicolas998/WMF#84]
Desde que se hizo la migración a Python 3.5 la función **wmf.Basin.Plot_basin** dejo de funcionar bien, es recomendable cambiarla del todo o hacer que trabaje.

**Comment by seospinale** [comment]
desde hace unos días encontré que basemap en las nuevas versiones supongo que por un error hace esto cuando se pone la barra de colores 
![image](https://user-images.githubusercontent.com/30450680/46908564-2c8e6a00-ceea-11e8-8497-27cef6ec45bb.png)

entonces la solución parece ser cambiar esto:

if colorbar:
                    cbar = m.colorbar(cs,location='bottom',pad="5%")

por esto:
if colorbar:
                    cbar = pl.colorbar(cs,orientation='horizontal',pad=0.05)

pero no he probado a fondo para ver que no se altere algo más, pero de momento parecce ser la solución, ejemplo:
![image](https://user-images.githubusercontent.com/30450680/46908575-75462300-ceea-11e8-8b88-51e11d1c43ae.png)

**Comment by seospinale** [comment]
No hay nada al respecto en los blog de basemap porque el soporte ya parece estar como muerto.

**Comment by nicolas998** [comment]
y si cambiamos a cartopy?

**Comment by nicolas998** [comment]
solucionado
